# This can be expected to reach 20.8 reward within an hour when using a V100 GPU
# (e.g. p3.2xl instance on AWS, and m4.4xl workers). It also can reach ~21 reward
# within an hour with fewer workers (e.g. 4-8) but less reliably.
pong-apex:
    env: PongNoFrameskip-v4
    run: ASQ
    trial_resources:
        cpu:
            eval: 4 + spec.config.num_workers
        gpu:
            eval: spec.config.num_workers
        extra_cpu:
            eval: 4 + spec.config.num_workers
    config:
        double_q: False
        target_network_update_freq: 50000
        num_workers: 8
        lr: .0001
        gamma: 0.99
        optimizer_config:
            num_replay_buffer_shards: 8
